environment:
  matrix:
    - nodejs_version: "lts"
    - nodejs_version: "Current"
    - nodejs_version: "6"
    - nodejs_version: "7"
    - nodejs_version: "8"
    - nodejs_version: "9"
    - nodejs_version: "10"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version

build: off